[ValidJetsProducer] add tight JetID for UL17/18
KIT-CMS/Artus pull request #30
Opened 2022-01-19 10:19 UTC by cverstege

This commit adds tight JetID for Ultra Legay 2017 and 2018.

This requires the JetID to be set in the Excalibur config. Does this cause any problems?
Before only the IDVersion (year) was checked and tightlepveto was applied by default.

2022-01-19 12:09 UTC, HerrHorizontal requested changes
You have quite a lot of duplicate code introduced. Since `tightlepveto` only adds two additional cuts to the JetID, it is easy to get rid of these duplications (see inline comments).

2022-01-19 12:09 UTC, HerrHorizontal commented on KappaAnalysis/interface/Producers/ValidJetsProducer.h
> +                    if (jetID == KappaEnumTypes::JetID::TIGHTLEPVETO) {
Add `|| TIGHT` to cover both cases ...

2022-01-19 12:09 UTC, HerrHorizontal commented on KappaAnalysis/interface/Producers/ValidJetsProducer.h
> +                              jet->chargedHadronFraction > minCHFraction &&
... and put this...

2022-01-19 12:09 UTC, HerrHorizontal commented on KappaAnalysis/interface/Producers/ValidJetsProducer.h
> +                              jet->electronFraction < maxCEMFraction))
... and this to an additional fanout, which only covers `tightlepveto` case.

And do the same below.

2022-01-19 15:51 UTC, cverstege commented
I'm not sure if checking for "tight" is correct. Since for UL there is only one JetId and additional LepVeto criteria.

2022-01-25 20:37 UTC, HerrHorizontal approved these changes
This looks good now. Thanks! :+1:

2022-01-25 20:38 UTC, merged